### ISSUE TITLE
Set pipeline for training using generator

### ISSUE THREAD

**Issue by marekhering** [cvlab-ai/splinter#21]
- Setting training pipeline
- Generated data augmentation
- Preparing the generator for creating training data with metadata
- Train model

**Comment by Debskij** [comment]
It would be worth it to be precise and explain tasks.
> * Generated data augmentation
Currently, there is a data generator that allows generating infinite amounts of synthetic data (with respect to configuration), but yet there are no options to augment data in a way to reflect scanning imperfections. To achieve better results with real data we want to add a feature that will allow us to generate more realistic data by adding imperfections.
> * Preparing the generator for creating training data with metadata
We need to adjust the output of the generator to make it work directly with the model training framework

**Comment by Debskij** [comment]
> * Setting training pipeline
> * Generated data augmentation
> * Preparing the generator for creating training data with metadata
> * Train model

In this issue, we've done 
> * Setting training pipeline
> * Generated data augmentation
> * Preparing the generator for creating training data with metadata

Due to current prioritization, our decision was to work on the training model later on as it seems to be a non-blocking task at the present stage
