### ISSUE TITLE
Create exam storage container

### ISSUE THREAD

**Issue by leckijakub** [cvlab-ai/splinter#22]
Imported exams should be stored in a dedicated docker container which would be accessible only inside the internal docker network.

**Comment by Debskij** [comment]
Hi @leckijakub!
I think that for clarity reasons we need a document describing an architecture concerning communication between services. It seems that even having a section in readme will be sufficient for that cause. 
Would you mind considering that as a part of this task?

**Comment by leckijakub** [comment]
HI @Debskij of course. The documentation which you are suggesting should be a separate task as it will reflect on our whole project. I'll create a ticket for this.

**Comment by leckijakub** [comment]
New ticket created https://github.com/cvlab-ai/splinter/issues/24

**Comment by leckijakub** [comment]
Changes merged in https://github.com/cvlab-ai/splinter/pull/37
