### ISSUE TITLE
Analysis of the collected data

### ISSUE THREAD

**Issue by Krystian030** [cvlab-ai/splinter#98]
The task involves preparing a report (accessible [here](https://docs.google.com/document/d/1avRp_1WuVwnJfVTzOtcZyqoS1FWSCD4qPa8ySQ2lXB4/edit?usp=sharing)) detailing the collected data, such as identifying numbers written in various styles.

**Comment by S-cichocka** [comment]
The data collected was analysed manually for errors and the way the numbers were written - the result in the sheet: [https://1drv.ms/x/s!AuEhl1NqT0N7iGGp7t45b_zb87Af?e=BqXnwQ](url)
